# Generated by Django 4.2.5 on 2024-09-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nametype', models.CharField(max_length=100)),
                ('discountName', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('actualPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nametype', models.CharField(max_length=100)),
                ('discountName', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('actualPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nametype', models.CharField(max_length=100)),
                ('discountName', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('actualPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nametype', models.CharField(max_length=100)),
                ('discountName', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('actualPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nametype', models.CharField(max_length=100)),
                ('discountName', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('actualPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nametype', models.CharField(max_length=100)),
                ('discountName', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('actualPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nametype', models.CharField(max_length=100)),
                ('discountName', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('actualPrice', models.IntegerField()),
            ],
        ),
    ]
