# Generated by Django 4.2.5 on 2024-09-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drluxury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination2',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination3',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination4',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination5',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination6',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination7',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
